package com.mycompany.logitrack.vista;
import com.mycompany.logitrack.modelo.ColaDinamica;
import com.mycompany.logitrack.modelo.Paquete;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.logitrack.controlador.LogiTrackControlador;
import com.mycompany.logitrack.modelo.Entrega;
import com.mycompany.logitrack.modelo.PilaDinamica;
/**
 *
 * @author allan
 */
public class FrmColaDespacho extends javax.swing.JFrame {
    
    private final ColaDinamica cola =
        LogiTrackControlador.getInstancia().getColaDespacho();
    
    private final PilaDinamica historial =
        LogiTrackControlador.getInstancia().getHistorialEntregas();
    
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form ColaDespacho
     */
    public FrmColaDespacho() {
    initComponents();

    modeloTabla = (DefaultTableModel) tblColaDespacho.getModel();

    setLocationRelativeTo(null);
    setTitle("LogiTrack - Cola de despacho");

    actualizarTabla();
    }
    
    private void actualizarTabla() {

    modeloTabla.setRowCount(0);

    for (Paquete paquete : cola.obtenerPaquetes()) {

        modeloTabla.addRow(new Object[]{
            paquete.getId(),
            paquete.getDescripcion(),
            paquete.getDestino(),
            paquete.getEstado()
        });
    }
    
    
}
    private boolean existePaquete(int id) {

    for (Paquete paquete : cola.obtenerPaquetes()) {

        if (paquete.getId() == id) {
            return true;
        }
    }

    return false;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblColaDespacho = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LogiTrack - Cola de Despacho");

        jLabel2.setText("Centro de Distribución:");

        jButton1.setText("Despachar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Registrar paquete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Volver ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblColaDespacho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID ", "Descripción ", "Destino ", "Estado "
            }
        ));
        jScrollPane1.setViewportView(tblColaDespacho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    if (cola.estaVacia()) {

        JOptionPane.showMessageDialog(
                this,
                "No hay paquetes pendientes en la cola.",
                "Cola vacía",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    Paquete paquete = cola.desencolar();
    paquete.setEstado("EN_TRANSITO");
    Entrega entrega = new Entrega(
        paquete.getId(),
        "Transportista",
        java.time.LocalDate.now().toString(),
        "ENTREGADO"
);

historial.apilar(entrega);

    JOptionPane.showMessageDialog(
            this,
            "Paquete despachado correctamente.\n\n"
            + "ID: " + paquete.getId()
            + "\nDescripción: " + paquete.getDescripcion()
            + "\nDestino: " + paquete.getDestino()
            + "\nEstado: " + paquete.getEstado(),
            "Despacho realizado",
            JOptionPane.INFORMATION_MESSAGE
    );

    actualizarTabla();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    try {

        String idTexto = JOptionPane.showInputDialog(
                this,
                "Ingrese el ID del paquete:",
                "Registrar paquete",
                JOptionPane.QUESTION_MESSAGE
        );

        if (idTexto == null) {
            return;
        }

        idTexto = idTexto.trim();

        if (idTexto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "El ID es obligatorio.",
                    "Dato inválido",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int id = Integer.parseInt(idTexto);

        if (id <= 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "El ID debe ser mayor que cero.",
                    "Dato inválido",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (existePaquete(id)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ya existe un paquete con el ID " + id + ".",
                    "ID duplicado",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String descripcion = JOptionPane.showInputDialog(
                this,
                "Ingrese la descripción del paquete:",
                "Registrar paquete",
                JOptionPane.QUESTION_MESSAGE
        );

        if (descripcion == null) {
            return;
        }

        descripcion = descripcion.trim();

        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "La descripción es obligatoria.",
                    "Dato inválido",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String destino = JOptionPane.showInputDialog(
                this,
                "Ingrese el destino del paquete:",
                "Registrar paquete",
                JOptionPane.QUESTION_MESSAGE
        );

        if (destino == null) {
            return;
        }

        destino = destino.trim();

        if (destino.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "El destino es obligatorio.",
                    "Dato inválido",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Paquete nuevoPaquete = new Paquete(
                id,
                descripcion,
                destino,
                "REGISTRADO"
        );

        cola.encolar(nuevoPaquete);

        actualizarTabla();

        JOptionPane.showMessageDialog(
                this,
                "Paquete registrado correctamente.\n"
                + "Posición en la cola: "
                + cola.obtenerCantidad(),
                "Registro exitoso",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (NumberFormatException ex) {

        JOptionPane.showMessageDialog(
                this,
                "El ID debe contener solamente números enteros.",
                "ID inválido",
                JOptionPane.ERROR_MESSAGE
        );
    }
    
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FrmMenuAdmin menu = new FrmMenuAdmin();
        menu.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmColaDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmColaDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmColaDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmColaDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmColaDespacho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblColaDespacho;
    // End of variables declaration//GEN-END:variables
}
