
package com.mycompany.logitrack.vista;
import com.mycompany.logitrack.controlador.LogiTrackControlador;
import com.mycompany.logitrack.persistencia.PersistenciaJSON;
import javax.swing.JOptionPane;
import java.io.IOException;


public class FrmMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public FrmMenuAdmin() {
    initComponents();

    setLocationRelativeTo(null);

    cargarDatos();
}
    
    private void cargarDatos() {

    try {

        PersistenciaJSON.cargar(
                LogiTrackControlador.getInstancia().getListaCentros(),
                LogiTrackControlador.getInstancia().getColaDespacho(),
                LogiTrackControlador.getInstancia().getHistorialEntregas()
        );

    } catch (IOException | IllegalArgumentException ex) {

        JOptionPane.showMessageDialog(
                this,
                "No fue posible cargar los datos guardados.\n"
                + ex.getMessage(),
                "Error de carga",
                JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnCentros = new javax.swing.JButton();
        btnColaDespacho = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnPaquetesCentro = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnHistorial.setText("Historial de Entregas");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnCentros.setText(" Gestión de Centros");
        btnCentros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentrosActionPerformed(evt);
            }
        });

        btnColaDespacho.setText("Cola de Despacho");
        btnColaDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaDespachoActionPerformed(evt);
            }
        });

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("LogiTrack - Menú Administrador");

        btnPaquetesCentro.setText("Paquetes por Centro");
        btnPaquetesCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaquetesCentroActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar datos");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(40, 40, 40)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPaquetesCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(btnCentros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColaDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(61, 61, 61)
                .addComponent(btnColaDespacho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCentros)
                .addGap(13, 13, 13)
                .addComponent(btnHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPaquetesCentro)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnGuardar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmSeleccionRol rol = new FrmSeleccionRol();
        rol.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        FrmHistorialEntregas historial = new FrmHistorialEntregas();
        historial.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnCentrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentrosActionPerformed
        FrmCentros centros = new FrmCentros();
        centros.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCentrosActionPerformed

    private void btnColaDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaDespachoActionPerformed
        FrmColaDespacho cola = new FrmColaDespacho();
        cola.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColaDespachoActionPerformed

    private void btnPaquetesCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaquetesCentroActionPerformed
        FrmPaquetesCentro ventana = new FrmPaquetesCentro();
        ventana.setVisible(true);
        this.dispose();

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaquetesCentroActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    
            try {

        PersistenciaJSON.guardar(
                LogiTrackControlador.getInstancia().getListaCentros(),
                LogiTrackControlador.getInstancia().getColaDespacho(),
                LogiTrackControlador.getInstancia().getHistorialEntregas()
        );

        JOptionPane.showMessageDialog(
                this,
                "Datos guardados correctamente.\n\n"
                + PersistenciaJSON.obtenerRutaArchivo(),
                "Guardado exitoso",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (IOException ex) {

        JOptionPane.showMessageDialog(
                this,
                "No fue posible guardar los datos.\n"
                + ex.getMessage(),
                "Error de guardado",
                JOptionPane.ERROR_MESSAGE
        );
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentros;
    private javax.swing.JButton btnColaDespacho;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnPaquetesCentro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
