
package com.mycompany.logitrack.vista;
import com.mycompany.logitrack.controlador.LogiTrackControlador;
import com.mycompany.logitrack.modelo.CentroDistribucion;
import com.mycompany.logitrack.modelo.ListaSimpleCentros;
import com.mycompany.logitrack.modelo.ListaDoblePaquetes;
import com.mycompany.logitrack.modelo.Paquete;
import javax.swing.JOptionPane;


public class FrmPaquetesCentro extends javax.swing.JFrame {
    
    private final ListaSimpleCentros listaCentros =
        LogiTrackControlador.getInstancia().getListaCentros();

private CentroDistribucion centroSeleccionado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPaquetesCentro.class.getName());

    /**
     * Creates new form FrmPaquetesCentro
     */
    public FrmPaquetesCentro() {
    initComponents();

    setLocationRelativeTo(null);
    setTitle("LogiTrack - Paquetes por centro");

    cargarCentros();
    actualizarFormulario();
}
    
    private void cargarCentros() {

    cboCentros.removeAllItems();

    for (CentroDistribucion centro : listaCentros.obtenerCentros()) {
        cboCentros.addItem(centro);
    }

    if (cboCentros.getItemCount() > 0) {
        cboCentros.setSelectedIndex(0);
        centroSeleccionado =
                (CentroDistribucion) cboCentros.getSelectedItem();
    } else {
        centroSeleccionado = null;
    }
}
    
    private void limpiarCampos() {
    txtIdPaquete.setText("");
    txtDescripcion.setText("");
    txtDestino.setText("");
    txtEstado.setText("");
}
    
    private void actualizarFormulario() {

    if (centroSeleccionado == null) {
        limpiarCampos();
        lblPosicion.setText("Paquete: 0 de 0");
        return;
    }

    ListaDoblePaquetes lista =
            centroSeleccionado.getListaPaquetes();

    Paquete paquete = lista.obtenerActual();

    if (paquete == null) {
        limpiarCampos();
        lblPosicion.setText("Paquete: 0 de 0");
        return;
    }

    txtIdPaquete.setText(
            String.valueOf(paquete.getId())
    );

    txtDescripcion.setText(
        paquete.getDescripcion()
);

    txtDestino.setText(
            paquete.getDestino()
    );

    txtEstado.setText(
            paquete.getEstado()
    );

    actualizarPosicion();
}
    
    private void actualizarPosicion() {

    if (centroSeleccionado == null) {
        lblPosicion.setText("Paquete: 0 de 0");
        return;
    }

    ListaDoblePaquetes lista =
            centroSeleccionado.getListaPaquetes();

    Paquete actual = lista.obtenerActual();

    if (actual == null) {
        lblPosicion.setText("Paquete: 0 de 0");
        return;
    }

    int posicion = 0;
    int contador = 1;

    for (Paquete paquete : lista.obtenerPaquetes()) {

        if (paquete == actual) {
            posicion = contador;
            break;
        }

        contador++;
    }

    lblPosicion.setText(
            "Paquete: " + posicion
            + " de " + lista.obtenerCantidad()
    );
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cboCentros = new javax.swing.JComboBox<>();
        txtIdPaquete = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblPosicion = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        ds = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboCentros.addActionListener(this::cboCentrosActionPerformed);
        txtIdPaquete.addActionListener(this::txtIdPaqueteActionPerformed);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Destino:");

        tf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tf.setText("descripcion: ");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Estado: ");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(this::btnAnteriorActionPerformed);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        lblPosicion.setText("Paquete: 0 de 0");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        ds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ds.setText("LogiTrack - Paquetes por centro");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Centro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnterior)
                                .addGap(18, 18, 18)
                                .addComponent(btnSiguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVolver)
                                    .addComponent(lblPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)))
                        .addComponent(btnEliminar)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboCentros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdPaquete, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDestino, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescripcion)
                            .addComponent(txtEstado, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(141, 141, 141))))
            .addComponent(ds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(ds)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCentros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(lblPosicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

    FrmMenuAdmin menu = new FrmMenuAdmin();
    menu.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cboCentrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCentrosActionPerformed
        centroSeleccionado =
            (CentroDistribucion) cboCentros.getSelectedItem();

    if (centroSeleccionado != null) {
        centroSeleccionado.getListaPaquetes().irAlInicio();
    }

    actualizarFormulario();

        // TODO add your handling code here:
    }//GEN-LAST:event_cboCentrosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         if (centroSeleccionado == null) {

        JOptionPane.showMessageDialog(
                this,
                "Primero debe registrar un centro de distribución.",
                "No hay centros",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    if (txtIdPaquete.getText().trim().isEmpty()
        || txtDescripcion.getText().trim().isEmpty()
        || txtDestino.getText().trim().isEmpty()
        || txtEstado.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Todos los campos son obligatorios.",
                "Datos incompletos",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        int id = Integer.parseInt(
                txtIdPaquete.getText().trim()
        );

        ListaDoblePaquetes lista =
                centroSeleccionado.getListaPaquetes();

        if (lista.buscarRecursivo(id) != null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ya existe un paquete con el ID " + id
                    + " en este centro.",
                    "ID duplicado",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        Paquete paquete = new Paquete(
        id,
        txtDescripcion.getText().trim(),
        txtDestino.getText().trim(),
        txtEstado.getText().trim()
);

        lista.agregar(paquete);

        lista.irAlInicio();

        while (lista.siguiente() != null) {
            // Avanza hasta el último paquete.
        }

        actualizarFormulario();

        JOptionPane.showMessageDialog(
                this,
                "Paquete agregado correctamente.",
                "Registro exitoso",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (NumberFormatException ex) {

        JOptionPane.showMessageDialog(
                this,
                "El ID debe contener solamente números enteros.",
                "ID inválido",
                JOptionPane.ERROR_MESSAGE
        );
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (centroSeleccionado == null) {
        return;
    }

    Paquete paquete =
            centroSeleccionado
                    .getListaPaquetes()
                    .anterior();

    if (paquete == null) {

        JOptionPane.showMessageDialog(
                this,
                "Ya se encuentra en el primer paquete.",
                "Inicio de la lista",
                JOptionPane.INFORMATION_MESSAGE
        );

        return;
    }

    actualizarFormulario();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
            if (centroSeleccionado == null) {
        return;
    }

    Paquete paquete =
            centroSeleccionado
                    .getListaPaquetes()
                    .siguiente();

    if (paquete == null) {

        JOptionPane.showMessageDialog(
                this,
                "Ya se encuentra en el último paquete.",
                "Final de la lista",
                JOptionPane.INFORMATION_MESSAGE
        );

        return;
    }

    actualizarFormulario();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
            if (centroSeleccionado == null) {
        return;
    }

    ListaDoblePaquetes lista =
            centroSeleccionado.getListaPaquetes();

    Paquete paquete = lista.obtenerActual();

    if (paquete == null) {

        JOptionPane.showMessageDialog(
                this,
                "No hay ningún paquete para eliminar.",
                "Lista vacía",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int respuesta = JOptionPane.showConfirmDialog(
            this,
            "¿Desea eliminar el paquete "
            + paquete.getId() + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
    );

    if (respuesta != JOptionPane.YES_OPTION) {
        return;
    }

    lista.eliminarActual();

    actualizarFormulario();

    JOptionPane.showMessageDialog(
            this,
            "Paquete eliminado correctamente.",
            "Eliminación exitosa",
            JOptionPane.INFORMATION_MESSAGE
    );
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed


    private void txtIdPaqueteActionPerformed(java.awt.event.ActionEvent evt) {
        if (centroSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Primero seleccione un centro.",
                    "No hay centro", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(txtIdPaquete.getText().trim());
            Paquete encontrado = centroSeleccionado.getListaPaquetes().buscarRecursivo(id);

            if (encontrado == null) {
                JOptionPane.showMessageDialog(this,
                        "No existe un paquete con el ID " + id + " en este centro.",
                        "Búsqueda recursiva", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            actualizarFormulario();
            JOptionPane.showMessageDialog(this,
                    "Paquete encontrado mediante búsqueda recursiva.",
                    "Búsqueda recursiva", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Digite un ID numérico y presione Enter para buscar.",
                    "ID inválido", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPaquetesCentro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<CentroDistribucion> cboCentros;
    private javax.swing.JLabel ds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblPosicion;
    private javax.swing.JLabel tf;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdPaquete;
    // End of variables declaration//GEN-END:variables
}
